name: test-env
channels:
  - conda-forge
dependencies:
  - fenics-dolfinx
  - pyvista
  - pip
  - jupyter-book
  - jupytext
  - trame-client
  - trame-vtk
  - trame-server
  - trame-vuetify
  - trame
  - ipywidgets
  - jupyterlab
  - trame-jupyter-extension
  - jupyter
variables:
  PYVISTA_OFF_SCREEN: false
  PYVISTA_JUPYTER_BACKEND: "trame"
  JUPYTER_EXTENSION_ENABLED: true
  LIBGL_ALWAYS_SOFTWARE: 1
